import bcrypt from 'bcryptjs'

const data = {
  users:[
    {
      name: 'Akash',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Praveen',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
     // _id: '1',
      name: 'Samsung Galaxy S20 Ultra',
      slug: 'samsung-galaxy-s20',
      countInStock: 10,
      category: 'Shirts',
      image: 'https://cdn1.smartprix.com/rx-itJdxy2gM-w420-h420/samsung-galaxy-s20-u.webp',
      price: 60000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
    //  _id: '2',
      name: 'Xiaomi 12 Pro',
      slug: 'xiaomi-12-pro',
      countInStock: 0,
      category: 'Shirts',
      image: 'https://cdn1.smartprix.com/rx-iJPWMTIXV-w420-h420/xiaomi-12-pro-5g-12g.webp',
      price: 55000,
      brand: ' Adidas',
      rating: 4.2,
      numReviews: 5,
      description: 'high quality product',
    },
    {
    //  _id: '3',
      name: 'Oneplus 10 Pro',
      slug: 'oneplus-10-pro',
      countInStock: 15,
      category: 'Pants',
      image: 'https://cdn1.smartprix.com/rx-iF7sjGtNc-w420-h420/oneplus-10-pro-5g-12.webp',
      price: 61000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
     // _id: '4',
      name: 'Iphone 13 Pro',
      slug: 'iphone-13-pro',
      countInStock: 5,
      category: 'Pant',
      image: 'https://cdn1.smartprix.com/rx-idCmB2rcl-w420-h420/apple-iphone-13-pro.webp',
      price: 120000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
     // _id: '5',
      name: 'Realme GT 2 Pro',
      slug: 'realme-gt-pro',
      countInStock: 5,
      category: 'Pant',
      image: 'https://cdn1.smartprix.com/rx-iuttJIsiy-w420-h420/realme-gt-2-pro-5g.webp',
      price: 44000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
    //  _id: '6',
      name: 'Vivo X80 Pro',
      slug: 'vivo-x80-pro',
      countInStock: 5,
      category: 'Pant',
      image: 'https://cdn1.smartprix.com/rx-iRMOxkU8b-w420-h420/vivo-x80-pro-5g.webp',
      price: 80000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
     // _id: '7',
      name: 'Sony Xperia 1 IV',
      slug: 'sony-xperia-1',
      countInStock: 5,
      category: 'Pant',
      image: 'https://cdn1.smartprix.com/rx-iL7Qnjhu8-w420-h420/sony-xperia-1-iv-12g.webp',
      price: 110000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
    //  _id: '8',
      name: 'Motorola Edge 30 Ultra',
      slug: 'motorola-edge-ultra',
      countInStock: 5,
      category: 'Pant',
      image: 'https://cdn1.smartprix.com/rx-iFeZKQDFl-w420-h420/motorola-edge-30-ult.webp',
      price: 54000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
  ],
};
export default data;
